#!/usr/bin/env python3
"""
Generate 40-question banks for all College subject quizzes
"""

# This file contains the question banks that will be inserted into each quiz HTML file
# Format: subject_name: list of 40 question dictionaries

QUESTION_BANKS = {
    "biology": [
        {"q": "What is the basic unit of life?", "opts": ["Atom", "Cell", "Molecule", "Tissue", "Organ"], "correct": 1, "exp": "The cell is the basic structural and functional unit of all living organisms. All life forms, from single-celled bacteria to complex multicellular organisms like humans, are composed of one or more cells. Cells contain the necessary components to carry out life processes."},
        {"q": "What is the process by which plants make their own food?", "opts": ["Respiration", "Photosynthesis", "Digestion", "Fermentation", "Transpiration"], "correct": 1, "exp": "Photosynthesis is the process by which green plants use sunlight, carbon dioxide, and water to produce glucose (food) and oxygen. This occurs primarily in the chloroplasts of plant cells and is essential for life on Earth as it produces oxygen and forms the base of most food chains."},
        {"q": "DNA stands for:", "opts": ["Deoxyribonucleic Acid", "Dinitrogen Acid", "Dual Nuclear Acid", "Deoxynitric Acid", "Dinucleotide Amino acid"], "correct": 0, "exp": "DNA (Deoxyribonucleic Acid) is the molecule that carries genetic information in all living organisms. It consists of two strands forming a double helix structure and contains the instructions needed for an organism to develop, survive, and reproduce."},
        {"q": "Which organelle is known as the 'powerhouse of the cell'?", "opts": ["Nucleus", "Ribosome", "Mitochondria", "Golgi apparatus", "Endoplasmic reticulum"], "correct": 2, "exp": "Mitochondria are called the powerhouse of the cell because they generate most of the cell's supply of ATP (adenosine triphosphate), which is used as a source of chemical energy. Through cellular respiration, mitochondria convert nutrients into energy the cell can use."},
        {"q": "What type of organism can make its own food?", "opts": ["Heterotroph", "Autotroph", "Decomposer", "Consumer", "Parasite"], "correct": 1, "exp": "Autotrophs are organisms that can produce their own food from inorganic substances. Plants, algae, and some bacteria are autotrophs that use photosynthesis or chemosynthesis to create energy-rich organic compounds from simple inorganic materials."},
        {"q": "The process of cell division in somatic cells is called:", "opts": ["Meiosis", "Mitosis", "Binary fission", "Budding", "Fragmentation"], "correct": 1, "exp": "Mitosis is the process of cell division that produces two genetically identical daughter cells from a single parent cell. It's used for growth, repair, and asexual reproduction in multicellular organisms. Somatic cells (body cells) divide through mitosis."},
        {"q": "What is evolution?", "opts": ["The growth of an organism over its lifetime", "Change in the inherited characteristics of populations over time", "The process of cell division", "The movement of organisms to new environments", "Individual adaptation to environment"], "correct": 1, "exp": "Evolution is the change in the inherited characteristics of biological populations over successive generations. It occurs through mechanisms like natural selection, genetic drift, and mutation, leading to the diversity of life we see today."},
        {"q": "In an ecosystem, organisms that produce their own food are called:", "opts": ["Consumers", "Decomposers", "Producers", "Predators", "Herbivores"], "correct": 2, "exp": "Producers (also called autotrophs) are organisms that can produce their own food through photosynthesis or chemosynthesis. They form the base of food chains and ecosystems, converting solar energy or chemical energy into organic compounds that other organisms can use."},
        {"q": "Which molecule carries genetic information from DNA to ribosomes?", "opts": ["tRNA", "mRNA", "rRNA", "DNA polymerase", "Proteins"], "correct": 1, "exp": "Messenger RNA (mRNA) carries genetic information from DNA in the nucleus to ribosomes in the cytoplasm, where proteins are synthesized. This process is called transcription (DNA to mRNA) followed by translation (mRNA to protein)."},
        {"q": "What is the function of ribosomes?", "opts": ["Energy production", "Protein synthesis", "Lipid synthesis", "DNA replication", "Cell division"], "correct": 1, "exp": "Ribosomes are cellular organelles responsible for protein synthesis. They read the genetic code carried by mRNA and assemble amino acids in the correct sequence to form proteins, which are essential for virtually all cellular functions."},
        
        # Questions 11-20
        {"q": "Which blood type is considered the universal donor?", "opts": ["A+", "B+", "AB+", "O-", "O+"], "correct": 3, "exp": "Type O- (O negative) blood is considered the universal donor because it lacks A, B, and Rh antigens, meaning it can be safely transfused to recipients of any blood type without triggering an immune response. This makes it extremely valuable in emergency situations."},
        {"q": "The genetic makeup of an organism is called its:", "opts": ["Phenotype", "Genotype", "Karyotype", "Allele", "Chromosome"], "correct": 1, "exp": "An organism's genotype is its complete genetic makeup - the specific set of genes it carries. This is distinct from the phenotype, which is the observable characteristics resulting from the interaction of genotype with the environment."},
        {"q": "What is the role of chlorophyll in photosynthesis?", "opts": ["Stores water", "Absorbs light energy", "Releases oxygen", "Produces glucose", "Absorbs carbon dioxide"], "correct": 1, "exp": "Chlorophyll is a green pigment in plants that absorbs light energy (primarily red and blue wavelengths) from the sun. This absorbed energy is then used to drive the photosynthetic process, converting carbon dioxide and water into glucose and oxygen."},
        {"q": "Osmosis is the movement of:", "opts": ["Water across a semipermeable membrane", "Glucose into cells", "Proteins through channels", "DNA during replication", "Ions against concentration gradient"], "correct": 0, "exp": "Osmosis is the passive movement of water molecules across a semipermeable membrane from an area of lower solute concentration to an area of higher solute concentration. This process is crucial for maintaining cell homeostasis and fluid balance in organisms."},
        {"q": "Which of the following is NOT a characteristic of living things?", "opts": ["Growth", "Reproduction", "Crystallization", "Metabolism", "Response to stimuli"], "correct": 2, "exp": "Crystallization is a physical/chemical process that occurs in non-living systems. The characteristics of living things include organization, metabolism, growth, adaptation, response to stimuli, reproduction, and homeostasis. Crystals grow but don't exhibit the other characteristics of life."},
        {"q": "What are the building blocks of proteins?", "opts": ["Nucleotides", "Amino acids", "Fatty acids", "Monosaccharides", "Phospholipids"], "correct": 1, "exp": "Proteins are made up of amino acids linked together by peptide bonds. There are 20 different amino acids that can be combined in various sequences to create the diverse array of proteins needed for life. Each amino acid has an amino group, carboxyl group, and unique side chain."},
        {"q": "The Hardy-Weinberg principle describes:", "opts": ["Protein synthesis", "Genetic equilibrium in populations", "Cell division", "Energy transfer", "Enzyme kinetics"], "correct": 1, "exp": "The Hardy-Weinberg principle states that allele and genotype frequencies in a population will remain constant from generation to generation in the absence of other evolutionary influences (mutation, gene flow, genetic drift, natural selection, non-random mating). It provides a baseline for studying evolution."},
        {"q": "What is the primary function of the Golgi apparatus?", "opts": ["Energy production", "DNA storage", "Protein packaging and modification", "Lipid synthesis", "Cell division"], "correct": 2, "exp": "The Golgi apparatus (or Golgi complex) is responsible for modifying, sorting, and packaging proteins and lipids for transport to their final destinations. It acts like a cellular post office, processing molecules from the endoplasmic reticulum and directing them to appropriate locations."},
        {"q": "Enzymes are primarily composed of:", "opts": ["Carbohydrates", "Lipids", "Proteins", "Nucleic acids", "Minerals"], "correct": 2, "exp": "Enzymes are biological catalysts that are primarily proteins (though some RNA molecules called ribozymes also have catalytic activity). They speed up chemical reactions by lowering activation energy without being consumed in the process. Each enzyme has a specific three-dimensional structure that determines its function."},
        {"q": "What is the function of the Krebs cycle?", "opts": ["Protein synthesis", "DNA replication", "Energy production through oxidation of acetyl-CoA", "Lipid synthesis", "Cell signaling"], "correct": 2, "exp": "The Krebs cycle (citric acid cycle) is a series of chemical reactions in cellular respiration that oxidizes acetyl-CoA to produce ATP, NADH, and FADH2. These energy-rich molecules are then used in the electron transport chain to generate large amounts of ATP. It occurs in the mitochondrial matrix."},
        
        # Questions 21-30
        {"q": "What determines the specificity of an antibody?", "opts": ["Its size", "Its variable region", "Its constant region", "Its charge", "Its location"], "correct": 1, "exp": "The variable region of an antibody determines its specificity. This region has a unique amino acid sequence that creates a specific three-dimensional shape complementary to a particular antigen (epitope). The vast diversity of variable regions allows the immune system to recognize millions of different antigens."},
        {"q": "Which process increases genetic variation in sexually reproducing organisms?", "opts": ["Mitosis", "Binary fission", "Meiosis and crossing over", "Budding", "Cloning"], "correct": 2, "exp": "Meiosis and crossing over (genetic recombination) increase genetic variation. During meiosis, homologous chromosomes exchange genetic material through crossing over, and independent assortment shuffles chromosomes into gametes. This creates genetically unique offspring, which is crucial for evolution and adaptation."},
        {"q": "What is the difference between prokaryotic and eukaryotic cells?", "opts": ["Size only", "Presence of cell wall", "Presence of membrane-bound nucleus", "Presence of ribosomes", "Ability to reproduce"], "correct": 2, "exp": "The fundamental difference is that eukaryotic cells have a membrane-bound nucleus and other membrane-bound organelles (like mitochondria, ER, Golgi), while prokaryotic cells lack these structures. Prokaryotes (bacteria and archaea) have their DNA in a nucleoid region, not enclosed by a membrane."},
        {"q": "What is homeostasis?", "opts": ["Cell division", "Maintaining stable internal conditions", "Energy production", "Genetic variation", "Evolution"], "correct": 1, "exp": "Homeostasis is the ability of an organism or cell to maintain stable internal conditions despite changes in the external environment. This includes regulating temperature, pH, glucose levels, water balance, and other physiological variables. It's essential for survival and proper functioning."},
        {"q": "Which cellular structure regulates what enters and exits the cell?", "opts": ["Cell wall", "Cytoplasm", "Plasma membrane", "Nucleus", "Ribosome"], "correct": 2, "exp": "The plasma membrane (cell membrane) is a selectively permeable barrier that regulates what enters and exits the cell. Composed of a phospholipid bilayer with embedded proteins, it controls the passage of ions, nutrients, wastes, and signaling molecules, maintaining cellular homeostasis."},
        {"q": "Natural selection acts on:", "opts": ["Genotype only", "Phenotype", "DNA sequences", "Chromosomes", "Mutations alone"], "correct": 1, "exp": "Natural selection acts on phenotypes - the observable characteristics of organisms. While genotypes determine potential traits, it's the expressed phenotype interacting with the environment that determines survival and reproductive success. Favorable phenotypes become more common over generations."},
        {"q": "What is the role of tRNA in protein synthesis?", "opts": ["Carries genetic code", "Brings amino acids to ribosomes", "Catalyzes peptide bonds", "Unwinds DNA", "Packages proteins"], "correct": 1, "exp": "Transfer RNA (tRNA) brings amino acids to the ribosome during translation. Each tRNA has an anticodon that pairs with a specific mRNA codon and carries the corresponding amino acid. This ensures amino acids are added in the correct sequence to form proteins."},
        {"q": "What is the primary difference between DNA and RNA?", "opts": ["DNA is double-stranded; RNA has uracil instead of thymine", "DNA is smaller than RNA", "RNA contains more genetic information", "DNA is found only in prokaryotes", "RNA cannot mutate"], "correct": 0, "exp": "Key differences include: DNA is typically double-stranded while RNA is single-stranded; DNA contains thymine while RNA contains uracil; DNA has deoxyribose sugar while RNA has ribose sugar. DNA stores genetic information long-term, while RNA primarily functions in protein synthesis and regulation."},
        {"q": "What is an ecosystem?", "opts": ["A single species population", "All living organisms in an area", "All living organisms and their physical environment interacting", "Only producers in an area", "The climate of a region"], "correct": 2, "exp": "An ecosystem includes all living organisms (biotic factors) in a particular area interacting with each other and with the non-living components (abiotic factors like water, soil, climate). Energy flows through ecosystems while nutrients cycle, creating complex interconnected relationships."},
        {"q": "What is the function of the endoplasmic reticulum?", "opts": ["DNA storage", "Energy production", "Protein and lipid synthesis", "Cell division", "Waste removal"], "correct": 2, "exp": "The endoplasmic reticulum (ER) is a network of membranes involved in protein and lipid synthesis. Rough ER (with ribosomes) synthesizes and modifies proteins, while smooth ER synthesizes lipids, metabolizes carbohydrates, detoxifies drugs, and stores calcium ions."},
        
        # Questions 31-40
        {"q": "What are vestigial structures?", "opts": ["Newly evolved features", "Structures with no apparent function inherited from ancestors", "Essential survival structures", "Structures unique to one species", "Structures that appeared spontaneously"], "correct": 1, "exp": "Vestigial structures are anatomical features that have lost most or all of their original function through evolution but are still present. Examples include the human appendix, wisdom teeth, and tailbone. They provide evidence for evolution and common ancestry."},
        {"q": "What is the role of stomata in plants?", "opts": ["Water storage", "Gas exchange and transpiration", "Photosynthesis", "Nutrient absorption", "Reproduction"], "correct": 1, "exp": "Stomata are small pores on plant leaves and stems that regulate gas exchange - allowing CO2 to enter for photosynthesis and oxygen to exit. They also control water loss through transpiration. Guard cells surrounding each stoma can open or close the pore based on environmental conditions."},
        {"q": "What is a mutation?", "opts": ["Normal cell division", "A change in DNA sequence", "Protein synthesis", "Energy production", "Cell death"], "correct": 1, "exp": "A mutation is a change in the DNA sequence of an organism's genome. Mutations can be caused by errors during DNA replication, exposure to mutagens (radiation, chemicals), or viral insertion. They can be beneficial, harmful, or neutral, and are the ultimate source of genetic variation."},
        {"q": "What is the difference between aerobic and anaerobic respiration?", "opts": ["Location in cell", "Aerobic requires oxygen; anaerobic does not", "Products produced", "Aerobic is faster", "Type of organism"], "correct": 1, "exp": "Aerobic respiration requires oxygen and produces significantly more ATP (about 36-38 molecules per glucose), along with CO2 and water. Anaerobic respiration (fermentation) occurs without oxygen and produces less ATP (2 molecules per glucose), along with lactic acid or ethanol. Aerobic is much more efficient."},
        {"q": "What is a food web?", "opts": ["A single food chain", "Complex network showing all feeding relationships in an ecosystem", "Only predator-prey relationships", "Plant distribution pattern", "Energy pyramid"], "correct": 1, "exp": "A food web is a complex network of interconnected food chains showing all the feeding relationships within an ecosystem. Unlike a simple linear food chain, food webs show that most organisms eat and are eaten by multiple other species, creating a realistic picture of energy flow and ecological interactions."},
        {"q": "What is the purpose of meiosis?", "opts": ["Growth and repair", "Producing genetically identical cells", "Producing gametes with half the chromosome number", "Protein synthesis", "Energy production"], "correct": 2, "exp": "Meiosis is a type of cell division that produces four gametes (sex cells: sperm or eggs) each with half the chromosome number of the parent cell. This reduction is essential for sexual reproduction - when gametes fuse during fertilization, the normal chromosome number is restored. Meiosis also increases genetic diversity through crossing over and independent assortment."},
        {"q": "What is the lock-and-key model describing?", "opts": ["DNA replication", "Enzyme-substrate specificity", "Cell membrane structure", "Photosynthesis", "Muscle contraction"], "correct": 1, "exp": "The lock-and-key model describes enzyme-substrate specificity. Like a key fitting into a specific lock, each enzyme has an active site with a specific shape that complements its substrate. Only substrates with the correct shape can bind to the enzyme's active site, explaining why enzymes are substrate-specific."},
        {"q": "What is symbiosis?", "opts": ["Competition between species", "Close long-term interaction between different species", "Predator-prey relationship only", "Same species cooperation", "Asexual reproduction"], "correct": 1, "exp": "Symbiosis is a close, long-term interaction between two different species. There are three main types: mutualism (both benefit), commensalism (one benefits, other unaffected), and parasitism (one benefits, other harmed). Examples include nitrogen-fixing bacteria in plant roots and cleaner fish with larger fish."},
        {"q": "What is the central dogma of molecular biology?", "opts": ["Evolution theory", "DNA → RNA → Protein", "Cell theory", "Energy flow", "Homeostasis principle"], "correct": 1, "exp": "The central dogma describes the flow of genetic information: DNA → RNA → Protein. DNA is transcribed into RNA (specifically mRNA), which is then translated into proteins. This fundamental principle explains how genetic information is expressed and how traits are determined at the molecular level."},
        {"q": "What is carrying capacity in ecology?", "opts": ["Amount an animal can carry", "Maximum population size an environment can sustain", "Energy in ecosystem", "Number of species", "Biomass of producers"], "correct": 1, "exp": "Carrying capacity is the maximum population size of a species that an environment can sustain indefinitely given the available resources (food, water, shelter, space). Populations tend to fluctuate around carrying capacity. When populations exceed it, resources become depleted, leading to decline through increased death rates or reduced birth rates."}
    ]
}

# Print JavaScript format for easy copy-paste
if __name__ == "__main__":
    for subject, questions in QUESTION_BANKS.items():
        print(f"\n\n=== {subject.upper()} QUESTIONS ===\n")
        for i, q in enumerate(questions, 1):
            print(f"    {{ // Question {i}")
            print(f'      question: "{q["q"]}",')
            print(f'      options: {q["opts"]},')
            print(f'      correct: {q["correct"]},')
            print(f'      explanation: "{q["exp"]}"')
            print("    },")
